#
#	PLEASE NOTE:
#
#	The Gradle build also uses ARTIFACTORY_USER and ARTIFACTORY_PASSWORD,
#	but DO NOT define them here of they will be saved into version control
#	where anyone can see them.
#
PROJECT_SOURCE_COMPATIBILITY=1.8
PROJECT_GROUP=com.tooltwist

# Make sure either both are snapshot, or neither are snapshot versions.
PROJECT_VERSION=5.0.0-SNAPSHOT
TOOLTWIST_VERSION=8.3.3-SNAPSHOT

# Properties related to publishing this project's artifacts
PUBLISH_CONTEXTURL=https\://tooltwist.jfrog.io/artifactory/
PUBLISH_SNAPSHOT_REPO=rpdata-snapshot-local
PUBLISH_RELEASE_REPO=rpdata-release-local
